<?php

/**
 * ZSELEX.
 *
 * @copyright R2International
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package ShopProducts
 * @author R2International <R2International>.
 * @link http://modulestudio.de/
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Tue Feb 07 21:56:43 IST 2012.
 */
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;
use DoctrineExtensions\Paginate\Paginate;
use Doctrine\ORM;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * Repository class used to implement own convenience methods for performing certain DQL queries.
 *
 * This is the base repository class for shop entities.
 */
class ZPayment_Entity_Repository_Freight extends ZSELEX_Entity_Repository_General {

    public function getDirectpay($args) {
        $shop_id = $args['shop_id'];
        $dql = "SELECT a.enabled , a.info 
                  FROM ZPayment_Entity_DirectpaySetting a 
                  WHERE a.shop_id = :shop_id";

        // echo $dql;

        $query = $this->_em->createQuery($dql);
        $query->setParameter('shop_id', $shop_id);
        $result = $query->getOneOrNullResult();
        //echo "<pre>";  print_r($result);   echo "</pre>";

        return $result; // hydrate result to array
    }

    public function directpay_count($args) {
        $shop_id = $args['shop_id'];
        $query = $this->_em->createQuery('SELECT COUNT(u.id) FROM ZPayment_Entity_DirectpaySetting u '
                . 'WHERE u.shop_id=:shop_id');
        $query->setParameter('shop_id', $shop_id);
        $count = $query->getSingleScalarResult();
        return $count;
    }

    public function updateDirectpaySettings($args) {
        // echo "<pre>"; print_r($args); echo "</pre>";  exit;

        $qb = $this->_em->createQueryBuilder();
        $q = $qb->update('ZPayment_Entity_DirectpaySetting', 'u')
                ->set('u.enabled', ':enabled')
                ->set('u.info', ':info')
                ->where('u.shop_id = :shop_id')
                ->setParameter('shop_id', $args['shop_id'])
                ->setParameter('enabled', $args['Directpay_enabled'])
                ->setParameter('info', $args['Directpay_info'])
                ->getQuery();
        $p = $q->execute();
        if ($p) {
            return $p;
        }
    }

}
