<?php

/**
 * ZSELEX.
 *
 * @copyright R2International
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package ShopProducts
 * @author R2International <R2International>.
 * @link http://modulestudio.de/
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Tue Feb 07 21:56:43 IST 2012.
 */
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;
use DoctrineExtensions\Paginate\Paginate;
use Doctrine\ORM;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * Repository class used to implement own convenience methods for performing certain DQL queries.
 *
 * This is the base repository class for shop entities.
 */
class ZPayment_Entity_Repository_Paypal extends ZSELEX_Entity_Repository_General {

    public function updatePaypalPayment($status, $orderId, $transactionId) {

        // $date = date("Y-m-d");
        $qb = $this->_em->createQueryBuilder();
        $q = $qb->update('ZPayment_Entity_Paypal', 'u')
                ->set('u.status', '?1')
                ->set('u.transaction_id', '?3')
                ->where('u.order_id = ?2')
                ->setParameter(1, $status)
                ->setParameter(2, $orderId)
                ->setParameter(3, $transactionId)
                ->getQuery();
        $p = $q->execute();
        return $p;
    }

    public function getPaypal($args) {
        $shop_id = $args['shop_id'];
        $dql = "SELECT a.enabled , a.test_mode , a.business_email
                  FROM ZPayment_Entity_PaypalSetting a 
                  WHERE a.shop_id = :shop_id";

        // echo $dql;

        $query = $this->_em->createQuery($dql);
        $query->setParameter('shop_id', $shop_id);
        $result = $query->getOneOrNullResult();
        //echo "<pre>";  print_r($result);   echo "</pre>";

        return $result; // hydrate result to array
    }

    public function paypal_count($args) {
        $shop_id = $args['shop_id'];
        $query = $this->_em->createQuery('SELECT COUNT(u.id) FROM ZPayment_Entity_PaypalSetting u '
                . 'WHERE u.shop_id=:shop_id');
        $query->setParameter('shop_id', $shop_id);
        $count = $query->getSingleScalarResult();
        return $count;
    }

    public function paypalTxnCount($args) {
        $transaction_id = $args['txn_id'];
        $query = $this->_em->createQuery('SELECT COUNT(u.transaction_id) FROM ZPayment_Entity_Paypal u '
                . 'WHERE u.transaction_id=:transaction_id');
        $query->setParameter('transaction_id', $transaction_id);
        $count = $query->getSingleScalarResult();
        return $count;
    }

    public function paypal_orderCount($args) {
        $order_id = $args['order_id'];
        $query = $this->_em->createQuery('SELECT COUNT(u.order_id) FROM ZPayment_Entity_Paypal u '
                . 'WHERE u.order_id=:order_id');
        $query->setParameter('order_id', $order_id);
        $count = $query->getSingleScalarResult();
        return $count;
    }

    public function updatePaypalSettings($args) {
        // echo "<pre>"; print_r($args); echo "</pre>";  exit;

        $qb = $this->_em->createQueryBuilder();
        $q = $qb->update('ZPayment_Entity_PaypalSetting', 'u')
                ->set('u.enabled', ':enabled')
                ->set('u.test_mode', ':test_mode')
                ->set('u.business_email', ':business_email')
                ->where('u.shop_id = :shop_id')
                ->setParameter('shop_id', $args['shop_id'])
                ->setParameter('enabled', $args['Paypal_enabled'])
                ->setParameter('test_mode', $args['Paypal_testmode'])
                ->setParameter('business_email', $args['Paypal_business_email'])
                ->getQuery();
        $p = $q->execute();
        if ($p) {
            return $p;
        }
    }

    public function paymentMode($args) {
        $shop_id = $args['shop_id'];
        $dql = "SELECT a.enabled , a.test_mode 
                  FROM ZPayment_Entity_PaypalSetting a 
                  WHERE a.shop_id = :shop_id";

        //echo $dql;

        $query = $this->_em->createQuery($dql);
        $query->setParameter('shop_id', $shop_id);
        $result = $query->getOneOrNullResult();
        //echo "<pre>";  print_r($result);   echo "</pre>";

        return $result; // hydrate result to array
    }

}
