<?php

namespace DoctrineProxy;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ZSELEX_Entity_ProductProxy extends \ZSELEX_Entity_Product implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function addCategory(\ZSELEX_Entity_ProductCategory $category = NULL)
    {
        $this->__load();
        return parent::addCategory($category);
    }

    public function removeCategory(\ZSELEX_Entity_ProductCategory $category)
    {
        $this->__load();
        return parent::removeCategory($category);
    }

    public function getProduct_id()
    {
        $this->__load();
        return parent::getProduct_id();
    }

    public function getProduct_name()
    {
        $this->__load();
        return parent::getProduct_name();
    }

    public function setProduct_name($product_name)
    {
        $this->__load();
        return parent::setProduct_name($product_name);
    }

    public function getShop()
    {
        $this->__load();
        return parent::getShop();
    }

    public function setShop(\ZSELEX_Entity_Shop $shop)
    {
        $this->__load();
        return parent::setShop($shop);
    }

    public function getUrltitle()
    {
        $this->__load();
        return parent::getUrltitle();
    }

    public function setUrltitle($urltitle)
    {
        $this->__load();
        return parent::setUrltitle($urltitle);
    }

    public function getPrd_description()
    {
        $this->__load();
        return parent::getPrd_description();
    }

    public function setPrd_description($prd_description)
    {
        $this->__load();
        return parent::setPrd_description($prd_description);
    }

    public function getKeywords()
    {
        $this->__load();
        return parent::getKeywords();
    }

    public function setKeywords($keywords)
    {
        $this->__load();
        return parent::setKeywords($keywords);
    }

    public function getOriginal_price()
    {
        $this->__load();
        return parent::getOriginal_price();
    }

    public function setOriginal_price($original_price)
    {
        $this->__load();
        return parent::setOriginal_price($original_price);
    }

    public function getPrd_price()
    {
        $this->__load();
        return parent::getPrd_price();
    }

    public function setPrd_price($prd_price)
    {
        $this->__load();
        return parent::setPrd_price($prd_price);
    }

    public function getDiscount()
    {
        $this->__load();
        return parent::getDiscount();
    }

    public function setDiscount($discount)
    {
        $this->__load();
        return parent::setDiscount($discount);
    }

    public function getPrd_quantity()
    {
        $this->__load();
        return parent::getPrd_quantity();
    }

    public function setPrd_quantity($prd_quantity)
    {
        $this->__load();
        return parent::setPrd_quantity($prd_quantity);
    }

    public function getPrd_image()
    {
        $this->__load();
        return parent::getPrd_image();
    }

    public function setPrd_image($prd_image)
    {
        $this->__load();
        return parent::setPrd_image($prd_image);
    }

    public function getManufacturer()
    {
        $this->__load();
        return parent::getManufacturer();
    }

    public function setManufacturer(\ZSELEX_Entity_Manufacturer $manufacturer)
    {
        $this->__load();
        return parent::setManufacturer($manufacturer);
    }

    public function getPrd_status()
    {
        $this->__load();
        return parent::getPrd_status();
    }

    public function setPrd_status($prd_status)
    {
        $this->__load();
        return parent::setPrd_status($prd_status);
    }

    public function getEnable_ques()
    {
        $this->__load();
        return parent::getEnable_ques();
    }

    public function setPrd_question($prd_question)
    {
        $this->__load();
        return parent::setPrd_question($prd_question);
    }

    public function getProduct_to_category()
    {
        $this->__load();
        return parent::getProduct_to_category();
    }

    public function setProduct_to_category($product_to_category)
    {
        $this->__load();
        return parent::setProduct_to_category($product_to_category);
    }

    public function setPrd_discounts($prd_discounts)
    {
        $this->__load();
        return parent::setPrd_discounts($prd_discounts);
    }

    public function getPrd_discounts()
    {
        $this->__load();
        return parent::getPrd_discounts();
    }

    public function setNo_vat($no_vat)
    {
        $this->__load();
        return parent::setNo_vat($no_vat);
    }

    public function getNo_vat()
    {
        $this->__load();
        return parent::getNo_vat();
    }

    public function setMax_discount($max_discount)
    {
        $this->__load();
        return parent::setMax_discount($max_discount);
    }

    public function getMax_discount()
    {
        $this->__load();
        return parent::getMax_discount();
    }

    public function getCr_date()
    {
        $this->__load();
        return parent::getCr_date();
    }

    public function setCr_date($cr_date)
    {
        $this->__load();
        return parent::setCr_date($cr_date);
    }

    public function getCr_uid()
    {
        $this->__load();
        return parent::getCr_uid();
    }

    public function setCr_uid($cr_uid)
    {
        $this->__load();
        return parent::setCr_uid($cr_uid);
    }

    public function getLu_date()
    {
        $this->__load();
        return parent::getLu_date();
    }

    public function setLu_date($lu_date)
    {
        $this->__load();
        return parent::setLu_date($lu_date);
    }

    public function getLu_uid()
    {
        $this->__load();
        return parent::getLu_uid();
    }

    public function setLu_uid($lu_uid)
    {
        $this->__load();
        return parent::setLu_uid($lu_uid);
    }

    public function getReflection()
    {
        $this->__load();
        return parent::getReflection();
    }

    public function offsetExists($key)
    {
        $this->__load();
        return parent::offsetExists($key);
    }

    public function offsetGet($key)
    {
        $this->__load();
        return parent::offsetGet($key);
    }

    public function offsetSet($key, $value)
    {
        $this->__load();
        return parent::offsetSet($key, $value);
    }

    public function offsetUnset($key)
    {
        $this->__load();
        return parent::offsetUnset($key);
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }

    public function merge(array $array)
    {
        $this->__load();
        return parent::merge($array);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'product_id', 'product_name', 'shop', 'urltitle', 'prd_description', 'manufacturer', 'keywords', 'original_price', 'prd_price', 'discount', 'shipping_price', 'prd_quantity', 'prd_image', 'enable_question', 'validate_question', 'prd_question', 'no_vat', 'prd_status', 'advertise', 'max_discount', 'cr_date', 'cr_uid', 'lu_date', 'lu_uid', 'product_options', 'product_options_values', 'quantity_discounts', 'product_to_category');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}