<?php
/**
 * ShopProducts.
 *
 * @copyright 
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package ShopProducts
 * @author  <>.
 * @link http://modulestudio.de/
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Tue Feb 07 21:56:43 IST 2012.
 */

/**
 * Event handler implementation class for error-related events.
 */
class ZSELEX_Listener_ErrorListner
{

    function frontcontrollerError(Zikula_Event $event)
    {
        /*
          $eventName = $event->getName();
          $subject   = $event->getSubject();
          mail('sharazkhanz@gmail.com', 'frontcontrollerError',
          $message   = $subject);
          mail('ken@citypilot.dk', 'frontcontrollerError', $message   = $subject);
         */
    }

    /**
     * Listener for the `systemerror` event.
     *
     * Invoked on any system error.
     * args gets `array('errorno' => $errno, 'errstr' => $errstr, 'errfile' => $errfile, 'errline' => $errline, 'errcontext' => $errcontext)`.
     */
    public static function systemError(Zikula_Event $event)
    {
        /*
          $eventName = $event->getName();

          $subject = $event->getSubject();
          mail('sharazkhanz@gmail.com', 'systemError', $message = $subject);
          mail('ken@citypilot.dk', 'systemError', $message = $subject);
         */
    }
}