<?php

/**
 * ZSELEX.
 *
 * @copyright 
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package ShopProducts
 * @author  <>.
 * @link http://modulestudio.de/
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Tue Feb 07 21:56:43 IST 2012.
 */
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Mapping\Annotation as Gedmo;
use DoctrineExtensions\StandardFields\Mapping\Annotation as ZK;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the base entity class for shop entities.
 *
 *
 * @ORM\Entity(repositoryClass="ZSELEX_Entity_Repository_AdvertiseRepo")
 * @ORM\Table(name="zselex_advertise")
 */
class ZSELEX_Entity_Advertise extends Zikula_EntityAccess {
	
	/**
	 * shop_id field (record shop_id)
	 *
	 * @ORM\Id
	 * @ORM\Column(type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	public $advertise_id = 0;
	
	/**
	 * @ORM\Column(length=255)
	 * 
	 * @var string $title.
	 */
	public $name = '';
	
	/**
	 * @ORM\ManyToOne(targetEntity="ZSELEX_Entity_AdvertisePrice", inversedBy="advertise_price")
	 * @ORM\JoinColumn(name="adprice_id", referencedColumnName="adprice_id")
	 */
	public $adprice;
	
	/**
	 * @ORM\Column(length=255)
	 * 
	 * @var string .
	 */
	public $advertise_type = '';
	
	/**
	 * @ORM\Column(length=255)
	 * 
	 * @var string .
	 */
	public $level = '';
	
	/**
	 * @ORM\ManyToOne(targetEntity="ZSELEX_Entity_Shop", cascade={"all"}, inversedBy="shop_ads")
	 * @ORM\JoinColumn(name="shop_id", referencedColumnName="shop_id")
	 */
	public $shop;
	
	/**
	 * @ORM\ManyToOne(targetEntity="ZSELEX_Entity_Country", cascade={"all"}, inversedBy="country_ads")
	 * @ORM\JoinColumn(name="country_id", referencedColumnName="country_id")
	 */
	public $country = null;
	
	/**
	 * @ORM\ManyToOne(targetEntity="ZSELEX_Entity_Region", cascade={"all"}, inversedBy="region_ads")
	 * @ORM\JoinColumn(name="region_id", referencedColumnName="region_id")
	 */
	public $region = null;
	
	/**
	 * @ORM\ManyToOne(targetEntity="ZSELEX_Entity_City", cascade={"all"}, inversedBy="city_ads")
	 * @ORM\JoinColumn(name="city_id", referencedColumnName="city_id")
	 */
	public $city = null;
	
	/**
	 * @ORM\ManyToOne(targetEntity="ZSELEX_Entity_Area", cascade={"all"}, inversedBy="area_ads")
	 * @ORM\JoinColumn(name="area_id", referencedColumnName="area_id")
	 */
	public $area = null;
	
	/**
	 * @ORM\Column(type="text")
	 * 
	 * @var text.
	 */
	public $description = '';
	
	/**
	 * @ORM\Column(type="text")
	 * 
	 * @var text.
	 */
	public $keywords = '';
	
	/**
	 * @ORM\Column(type="integer")
	 * 
	 * @var int.
	 */
	public $maxviews = - 1;
	
	/**
	 * @ORM\Column(type="integer")
	 * 
	 * @var int.
	 */
	public $totalviews = '';
	
	/**
	 * @ORM\Column(type="integer")
	 * 
	 * @var int.
	 */
	public $viewstoday = '';
	
	/**
	 * @ORM\Column(type="integer")
	 * 
	 * @var int.
	 */
	public $maxclicks = - 1;
	
	/**
	 * @ORM\Column(type="integer")
	 * 
	 * @var int.
	 */
	public $totalclicks = '';
	
	/**
	 * @ORM\Column(type="integer")
	 * 
	 * @var int.
	 */
	public $clickstoday = '';
	
	/**
	 * @ORM\Column(type="date" , nullable=true)
	 * 
	 * @var date.
	 */
	public $startdate = null;
	
	/**
	 * @ORM\Column(type="date" , nullable=true)
	 * 
	 * @var date.
	 */
	public $enddate = null;
	
	/**
	 * @ORM\Column(type="boolean")
	 * 
	 * @var boolean.
	 */
	public $status = '';
	
	/**
	 * @ORM\Column(type="datetime")
	 * @Gedmo\Timestampable(on="create")
	 * 
	 * @var datetime $cr_date.
	 */
	public $cr_date;
	
	/**
	 * @ORM\Column(type="integer")
	 * @ZK\StandardFields(type="userid", on="create")
	 * 
	 * @var integer $cr_uid.
	 */
	public $cr_uid;
	
	/**
	 * @ORM\Column(type="datetime")
	 * @Gedmo\Timestampable(on="create")
	 * 
	 * @var datetime $lu_date.
	 */
	public $lu_date;
	
	/**
	 * @ORM\Column(type="integer")
	 * @ZK\StandardFields(type="userid", on="update")
	 * 
	 * @var integer $lu_uid.
	 */
	public $lu_uid;
	
	/**
	 * Constructor.
	 * Will not be called by Doctrine and can therefore be used
	 * for own implementation purposes. It is also possible to add
	 * arbitrary arguments as with every other class method.
	 */
	public function __construct() {
	}
	
	/**
	 * Get id.
	 *
	 * @return integer
	 */
	public function getAdvertise_id() {
		return $this->advertise_id;
	}
	
	/**
	 *
	 * @return string
	 */
	public function getName() {
		return $this->name;
	}
	
	/**
	 * Set name.
	 * 
	 * @param string $title.        	
	 * @return void
	 */
	public function setName($name) {
		$this->name = $name;
	}
	public function getAdprice() {
		return $this->adprice;
	}
	public function setAdprice(ZSELEX_Entity_AdvertisePrice $adprice) {
		$this->adprice = $adprice;
	}
	
	/**
	 * Get advertise_type.
	 *
	 * @return void
	 */
	public function getAdvertise_type() {
		return $this->advertise_type;
	}
	
	/**
	 * Set advertise_type.
	 * 
	 * @param string $advertise_type.        	
	 * @return void
	 */
	public function setAdvertise_type($advertise_type) {
		$this->advertise_type = $advertise_type;
	}
	
	/**
	 * Get level.
	 * 
	 * @return string
	 */
	public function getLevel() {
		return $this->level;
	}
	
	/**
	 * Set level.
	 * 
	 * @param string $level.        	
	 */
	public function setLevel($level) {
		$this->level = $level;
	}
	
	/**
	 * Get shop id.
	 * 
	 * @return string
	 */
	public function getShop() {
		return $this->shop;
	}
	
	/**
	 * Set shop.
	 * 
	 * @param int $shop.        	
	 */
	public function setShop(ZSELEX_Entity_Shop $shop) {
		$this->shop = $shop;
	}
	
	/**
	 * get the Country
	 * 
	 * @return integer
	 */
	public function getCountry() {
		return $this->country;
	}
	
	/**
	 * set the Country
	 * 
	 * @param string $country        	
	 */
	public function setCountry(ZSELEX_Entity_Country $country) {
		$this->country = $country;
	}
	
	/**
	 * get the Region
	 * 
	 * @return integer
	 */
	public function getRegion() {
		return $this->region;
	}
	
	/**
	 * set the Region
	 * 
	 * @param string $Region        	
	 */
	public function setRegion(ZSELEX_Entity_Region $region) {
		$this->region = $region;
	}
	
	/**
	 * get the City
	 * 
	 * @return integer
	 */
	public function getCity() {
		return $this->city;
	}
	
	/**
	 * set the City
	 * 
	 * @param string $city        	
	 */
	public function setCity(ZSELEX_Entity_City $city) {
		$this->city = $city;
	}
	
	/**
	 * get the Area
	 * 
	 * @return integer
	 */
	public function getArea() {
		return $this->area;
	}
	
	/**
	 * set the City
	 * 
	 * @param string $city        	
	 */
	public function setArea(ZSELEX_Entity_Area $area) {
		$this->area = $area;
	}
	
	/**
	 * get the description
	 * 
	 * @return text
	 */
	public function getDescription() {
		return $this->description;
	}
	
	/**
	 * set the description
	 * 
	 * @param
	 *        	text
	 */
	public function setDescription($description) {
		$this->description = $description;
	}
	
	/**
	 * get the keywords
	 * 
	 * @return text
	 */
	public function getKeywords() {
		return $this->keywords;
	}
	
	/**
	 * set the keywords
	 * 
	 * @param
	 *        	text
	 */
	public function setKeywords($keywords) {
		$this->keywords = $keywords;
	}
	
	/**
	 * get the maxviews
	 * 
	 * @return int
	 */
	public function getMaxviews() {
		return $this->maxviews;
	}
	
	/**
	 * set the maxviews
	 * 
	 * @param
	 *        	int
	 */
	public function setMaxviews($maxviews) {
		$this->maxviews = $maxviews;
	}
	
	/**
	 * get the totalviews
	 * 
	 * @return int
	 */
	public function getTotalviews() {
		return $this->totalviews;
	}
	
	/**
	 * set the totalviews
	 * 
	 * @param
	 *        	int
	 */
	public function setTotalviews($totalviews) {
		$this->totalviews = $totalviews;
	}
	
	/**
	 * get the viewstoday
	 * 
	 * @return int
	 */
	public function getViewstoday() {
		return $this->viewstoday;
	}
	
	/**
	 * set the viewstoday
	 * 
	 * @param
	 *        	int
	 */
	public function setViewstoday($viewstoday) {
		$this->viewstoday = $viewstoday;
	}
	
	/**
	 * get the maxclicks
	 * 
	 * @return int
	 */
	public function getMaxclicks() {
		return $this->maxclicks;
	}
	
	/**
	 * set the maxclicks
	 * 
	 * @param
	 *        	int
	 */
	public function setMaxclicks($maxclicks) {
		$this->maxclicks = $maxclicks;
	}
	
	/**
	 * get the totalclicks
	 * 
	 * @return int
	 */
	public function getTotalclicks() {
		return $this->totalclicks;
	}
	
	/**
	 * set the totalclicks
	 * 
	 * @param
	 *        	int
	 */
	public function setTotalclicks($totalclicks) {
		$this->totalclicks = $totalclicks;
	}
	
	/**
	 * get the clickstoday
	 * 
	 * @return int
	 */
	public function getClickstoday() {
		return $this->clickstoday;
	}
	
	/**
	 * set the clickstoday
	 * 
	 * @param
	 *        	int
	 */
	public function setClickstoday($clickstoday) {
		$this->clickstoday = $clickstoday;
	}
	
	/**
	 * get the startdate
	 * 
	 * @return date
	 */
	public function getStartdate() {
		return $this->startdate;
	}
	
	/**
	 * set the startdate
	 * 
	 * @param
	 *        	date
	 */
	public function setStartdate($startdate) {
		$this->startdate = $startdate;
	}
	
	/**
	 * get the enddate
	 * 
	 * @return date
	 */
	public function getEnddate() {
		return $this->enddate;
	}
	
	/**
	 * set the enddate
	 * 
	 * @param
	 *        	date
	 */
	public function setEnddate($enddate) {
		$this->enddate = $enddate;
	}
	
	/**
	 *
	 * @return integer
	 */
	public function getStatus() {
		return $this->status;
	}
	
	/**
	 *
	 * @return void
	 */
	public function setStatus($status) {
		if ($status != $this->status) {
			$this->status = $status;
		}
	}
	
	/**
	 * Get created user id.
	 *
	 * @return integer[]
	 */
	public function getCr_date() {
		return $this->cr_date;
	}
	
	/**
	 * Set created user id.
	 *
	 * @param integer[] $createdUserId.        	
	 *
	 * @return void
	 */
	public function setCr_date($cr_date) {
		$this->cr_date = $cr_date;
	}
	
	/**
	 * Get updated user id.
	 *
	 * @return integer[]
	 */
	public function getCr_uid() {
		return $this->cr_uid;
	}
	
	/**
	 * Set updated user id.
	 *
	 * @param integer[] $updatedUserId.        	
	 *
	 * @return void
	 */
	public function setCr_uid($cr_uid) {
		$this->cr_uid = $cr_uid;
	}
	
	/**
	 * Get created date.
	 *
	 * @return datetime[]
	 */
	public function getLu_date() {
		return $this->lu_date;
	}
	
	/**
	 * Set created date.
	 *
	 * @param datetime[] $createdDate.        	
	 *
	 * @return void
	 */
	public function setLu_date($lu_date) {
		$this->lu_date = $lu_date;
	}
	
	/**
	 * Get updated date.
	 *
	 * @return datetime[]
	 */
	public function getLu_uid() {
		return $this->lu_uid;
	}
	
	/**
	 * Get updated date.
	 *
	 * @return datetime[]
	 */
	public function setLu_uid($lu_uid) {
		$this->lu_uid = $lu_uid;
	}
	
	/**
	 * Post-Process the data after the entity has been constructed by the entity manager.
	 * The event happens after the entity has been loaded from database or after a refresh call.
	 *
	 * Restrictions:
	 * - no access to entity manager or unit of work apis
	 * - no access to associations (not initialised yet)
	 *
	 * @see ShopProducts_Entity_Shop::postLoadCallback()
	 * @return boolean true if completed successfully else false.
	 */
	protected function performPostLoadCallback() {
		// echo 'loaded a record ...';
		
		/*
		 * $currentType = FormUtil::getPassedValue('type', 'user', 'GETPOST', FILTER_SANITIZE_STRING);
		 * $currentFunc = FormUtil::getPassedValue('func', 'main', 'GETPOST', FILTER_SANITIZE_STRING);
		 *
		 * $this['id'] = (int) ((isset($this['id']) && !empty($this['id'])) ? DataUtil::formatForDisplay($this['id']) : 0);
		 * if ($currentFunc != 'edit') {
		 * $this['shop_name'] = ((isset($this['shop_name']) && !empty($this['shop_name'])) ? DataUtil::formatForDisplayHTML($this['shop_name']) : '');
		 * }
		 * if ($currentFunc != 'edit') {
		 * $this['address'] = ((isset($this['address']) && !empty($this['address'])) ? DataUtil::formatForDisplayHTML($this['address']) : '');
		 * }
		 * $this->prepareItemActions();
		 */
		return true;
	}
	
	/**
	 * Pre-Process the data prior to an insert operation.
	 * The event happens before the entity managers persist operation is executed for this entity.
	 *
	 * Restrictions:
	 * - no access to entity manager or unit of work apis
	 * - no identifiers available if using an identity generator like sequences
	 * - Doctrine won't recognize changes on relations which are done here
	 * if this method is called by cascade persist
	 * - no creation of other entities allowed
	 *
	 * @see ShopProducts_Entity_Shop::prePersistCallback()
	 * @return boolean true if completed successfully else false.
	 */
	protected function performPrePersistCallback() {
		// echo 'inserting a record ...';
		// $this->validate();
		return true;
	}
	
	/**
	 * Post-Process the data after an insert operation.
	 * The event happens after the entity has been made persistant.
	 * Will be called after the database insert operations.
	 * The generated primary key values are available.
	 *
	 * Restrictions:
	 * - no access to entity manager or unit of work apis
	 *
	 * @see ShopProducts_Entity_Shop::postPersistCallback()
	 * @return boolean true if completed successfully else false.
	 */
	protected function performPostPersistCallback() {
		// echo 'inserted a record ...';
		return true;
	}
	
	/**
	 * Pre-Process the data prior a delete operation.
	 * The event happens before the entity managers remove operation is executed for this entity.
	 *
	 * Restrictions:
	 * - no access to entity manager or unit of work apis
	 * - will not be called for a DQL DELETE statement
	 *
	 * @see ShopProducts_Entity_Shop::preRemoveCallback()
	 * @return boolean true if completed successfully else false.
	 */
	protected function performPreRemoveCallback() {
		/*
		 * // delete workflow for this entity
		 * $result = Zikula_Workflow_Util::deleteWorkflow($this);
		 * if ($result === false) {
		 * $dom = ZLanguage::getModuleDomain('ShopProducts');
		 * return LogUtil::registerError(__('Error! Could not remove stored workflow.', $dom));
		 * }
		 */
		return true;
	}
	
	/**
	 * Post-Process the data after a delete.
	 * The event happens after the entity has been deleted.
	 * Will be called after the database delete operations.
	 *
	 * Restrictions:
	 * - no access to entity manager or unit of work apis
	 * - will not be called for a DQL DELETE statement
	 *
	 * @see ShopProducts_Entity_Shop::postRemoveCallback()
	 * @return boolean true if completed successfully else false.
	 */
	protected function performPostRemoveCallback() {
		// echo 'deleted a record ...';
		return true;
	}
	
	/**
	 * Pre-Process the data prior to an update operation.
	 * The event happens before the database update operations for the entity data.
	 *
	 * Restrictions:
	 * - no access to entity manager or unit of work apis
	 * - will not be called for a DQL UPDATE statement
	 * - changes on associations are not allowed and won't be recognized by flush
	 * - changes on properties won't be recognized by flush as well
	 * - no creation of other entities allowed
	 *
	 * @see ShopProducts_Entity_Shop::preUpdateCallback()
	 * @return boolean true if completed successfully else false.
	 */
	protected function performPreUpdateCallback() {
		// echo 'updating a record ...';
		// $this->validate();
		return true;
	}
	
	/**
	 * Post-Process the data after an update operation.
	 * The event happens after the database update operations for the entity data.
	 *
	 * Restrictions:
	 * - no access to entity manager or unit of work apis
	 * - will not be called for a DQL UPDATE statement
	 *
	 * @see ShopProducts_Entity_Shop::postUpdateCallback()
	 * @return boolean true if completed successfully else false.
	 */
	protected function performPostUpdateCallback() {
		// echo 'updated a record ...';
		return true;
	}
	
	/**
	 * Pre-Process the data prior to a save operation.
	 * This combines the PrePersist and PreUpdate events.
	 * For more information see corresponding callback handlers.
	 *
	 * @see ShopProducts_Entity_Shop::preSaveCallback()
	 * @return boolean true if completed successfully else false.
	 */
	protected function performPreSaveCallback() {
		// echo 'saving a record ...';
		// $this->validate();
		return true;
	}
	
	/**
	 * Post-Process the data after a save operation.
	 * This combines the PostPersist and PostUpdate events.
	 * For more information see corresponding callback handlers.
	 *
	 * @see ShopProducts_Entity_Shop::postSaveCallback()
	 * @return boolean true if completed successfully else false.
	 */
	protected function performPostSaveCallback() {
		// echo 'saved a record ...';
		return true;
	}
}
