<?php

/**
 * ZSELEX.
 *
 * @copyright 
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package ShopProducts
 * @author  <>.
 * @link http://modulestudio.de/
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Tue Feb 07 21:56:43 IST 2012.
 */
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Mapping\Annotation as Gedmo;
use DoctrineExtensions\StandardFields\Mapping\Annotation as ZK;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the base entity class for shop entities.
 *
 *
 * @ORM\Entity(repositoryClass="ZSELEX_Entity_Repository_BundleRepo")
 * @ORM\Table(name="zselex_service_demo",indexes={@ORM\index(name="search", columns={"shop_id","bundle_id"})})
 */
class ZSELEX_Entity_ServiceDemo extends Zikula_EntityAccess {
	
	/**
	 * type_id field (record type_id)
	 *
	 * @ORM\Id
	 * @ORM\Column(type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	public $demo_id = 0;
	
	/**
	 * @ORM\ManyToOne(targetEntity="ZSELEX_Entity_Shop", inversedBy="shop_service_demo_bundles")
	 * @ORM\JoinColumn(name="shop_id", referencedColumnName="shop_id")
	 */
	public $shop = null;
	
	/**
	 * @ORM\Column(type="integer" , nullable=true)
	 */
	public $plugin_id = 0;
	
	/**
	 * @ORM\Column(length=255 , nullable=true)
	 */
	public $type = '';
	
	/**
	 * @ORM\Column(type="integer" , nullable=true)
	 */
	public $user_id = '';
	
	/**
	 * @ORM\Column(type="integer" , nullable=true)
	 */
	public $owner_id = 0;
	
	/**
	 * @ORM\Column(type="integer")
	 */
	public $quantity = 0;
	
	/**
	 * @ORM\Column(type="integer" , nullable=true)
	 */
	public $availed = 0;
	
	/**
	 * @ORM\Column(type="boolean")
	 */
	public $qty_based = 0;
	
	/**
	 * @ORM\Column(type="boolean" , nullable=true)
	 */
	public $is_bundle = 0;
	
	/**
	 * @ORM\ManyToOne(targetEntity="ZSELEX_Entity_Bundle", inversedBy="bundle_demos")
	 * @ORM\JoinColumn(name="bundle_id", referencedColumnName="bundle_id")
	 */
	public $bundle = null;
	
	/**
	 * @ORM\Column(type="boolean")
	 */
	public $top_bundle = 0;
	
	/**
	 * @ORM\Column(length=255)
	 */
	public $bundle_type = '';
	
	/**
	 * @ORM\Column(type="boolean")
	 */
	public $status = 0;
	
	/**
	 * @ORM\Column(type="date")
	 * 
	 * @var datetime $cr_date.
	 */
	public $start_date;
	
	/**
	 * @ORM\Column(type="integer")
	 */
	public $timer_days;
	
	/**
	 * Constructor.
	 * Will not be called by Doctrine and can therefore be used
	 * for own implementation purposes. It is also possible to add
	 * arbitrary arguments as with every other class method.
	 */
	public function __construct() {
		/*
		 * $this->id = 1;
		 * $this->_idFields = array('id');
		 * $this->initValidator();
		 * $this->_hasUniqueSlug = false;
		 * $this->products = new ArrayCollection();
		 *
		 */
		// $this->shop_areas = new ArrayCollection();
	}
	
	/**
	 * Get id.
	 *
	 * @return integer
	 */
	public function getDemo_id() {
		return $this->demo_id;
	}
	
	/**
	 * Get shop_name.
	 *
	 * @return string
	 */
	public function getShop() {
		return $this->shop;
	}
	
	/**
	 * Set area_name.
	 *
	 * @param string $area_name.        	
	 *
	 * @return void
	 */
	public function setShop(ZSELEX_Entity_Shop $shop) {
		$this->shop = $shop;
	}
	
	/**
	 * Get plugin.
	 */
	public function getPlugin() {
		return $this->plugin;
	}
	
	/**
	 * Set plugin.
	 */
	public function setPlugin_id($plugin_id) {
		$this->plugin_id = $plugin_id;
	}
	
	/**
	 * get the desc
	 * 
	 * @return integer
	 */
	public function getType() {
		return $this->type;
	}
	
	/**
	 * set the type
	 * 
	 * @param string $module        	
	 */
	public function setType($type) {
		$this->type = $type;
	}
	
	/**
	 * Get user id.
	 */
	public function getUser_id() {
		return $this->user_id;
	}
	
	/**
	 */
	
	public function setUser_id($user_id) {
		$this->user_id = $user_id;
	}
	
	/**
	 * Get owner_id.
	 *
	 * @return integer
	 */
	public function getOwner_id() {
		return $this->owner_id;
	}
	
	/**
	 * Set owner_id.
	 *
	 * @param
	 *        	integer owner_id.
	 *        	
	 */
	public function setOwner_id($owner_id) {
		$this->owner_id = $owner_id;
	}
	
	/**
	 * Get quantity.
	 * 
	 * @return integer
	 */
	public function getQuantity() {
		return $this->quantity;
	}
	
	/**
	 * Set quantity.
	 */
	public function setQuantity($quantity) {
		$this->quantity = $quantity;
	}
	
	/**
	 * Get availed.
	 * 
	 * @return integer
	 */
	public function getAvailed() {
		return $this->availed;
	}
	
	/**
	 * Set quantity.
	 */
	public function setAvailed($availed) {
		$this->availed = $availed;
	}
	
	/**
	 * Get qty_based.
	 * 
	 * @return integer
	 */
	public function getQty_based() {
		return $this->qty_based;
	}
	
	/**
	 * Set qty_based.
	 */
	public function setQty_based($qty_based) {
		$this->qty_based = $qty_based;
	}
	
	/**
	 * Get bundle.
	 * 
	 * @return integer
	 */
	public function getIs_bundle() {
		return $this->is_bundle;
	}
	
	/**
	 * Set qty_based.
	 */
	public function setIs_bundle($is_bundle) {
		$this->is_bundle = $is_bundle;
	}
	
	/**
	 * Get bundle.
	 * 
	 * @return integer
	 */
	public function getBundle() {
		return $this->bundle;
	}
	
	/**
	 * Set qty_based.
	 */
	public function setBundle(ZSELEX_Entity_Bundle $bundle) {
		$this->bundle = $bundle;
	}
	
	/**
	 * Get bundle.
	 * 
	 * @return integer
	 */
	public function getTop_bundle() {
		return $this->top_bundle;
	}
	
	/**
	 * Set qty_based.
	 */
	public function setTop_bundle($top_bundle) {
		$this->top_bundle = $top_bundle;
	}
	
	/**
	 * Get bundle_type.
	 * 
	 * @return string
	 */
	public function getBundle_type() {
		return $this->bundle_type;
	}
	
	/**
	 * Set bundle_type.
	 */
	public function setBundle_type($bundle_type) {
		$this->bundle_type = $bundle_type;
	}
	
	/**
	 * Get status.
	 * 
	 * @return integer
	 */
	public function getStatus() {
		return $this->status;
	}
	
	/**
	 * Set quantity.
	 */
	public function setStatus($status) {
		$this->status = $status;
	}
	
	/**
	 * Get timer_date.
	 * 
	 * @return string
	 */
	public function getStart_date() {
		return $this->start_date;
	}
	
	/**
	 * Set timer_date.
	 */
	public function setStart_date($start_date) {
		$this->start_date = $start_date;
	}
	public function setTimer_days($timer_days) {
		$this->timer_days = $timer_days;
	}
	public function getTimer_days() {
		return $this->timer_days;
	}
	
	/**
	 * Post-Process the data after the entity has been constructed by the entity manager.
	 * The event happens after the entity has been loaded from database or after a refresh call.
	 *
	 * Restrictions:
	 * - no access to entity manager or unit of work apis
	 * - no access to associations (not initialised yet)
	 *
	 * @see ShopProducts_Entity_Shop::postLoadCallback()
	 * @return boolean true if completed successfully else false.
	 */
	protected function performPostLoadCallback() {
		// echo 'loaded a record ...';
		
		/*
		 * $currentType = FormUtil::getPassedValue('type', 'user', 'GETPOST', FILTER_SANITIZE_STRING);
		 * $currentFunc = FormUtil::getPassedValue('func', 'main', 'GETPOST', FILTER_SANITIZE_STRING);
		 *
		 * $this['id'] = (int) ((isset($this['id']) && !empty($this['id'])) ? DataUtil::formatForDisplay($this['id']) : 0);
		 * if ($currentFunc != 'edit') {
		 * $this['shop_name'] = ((isset($this['shop_name']) && !empty($this['shop_name'])) ? DataUtil::formatForDisplayHTML($this['shop_name']) : '');
		 * }
		 * if ($currentFunc != 'edit') {
		 * $this['address'] = ((isset($this['address']) && !empty($this['address'])) ? DataUtil::formatForDisplayHTML($this['address']) : '');
		 * }
		 * $this->prepareItemActions();
		 */
		return true;
	}
	
	/**
	 * Pre-Process the data prior to an insert operation.
	 * The event happens before the entity managers persist operation is executed for this entity.
	 *
	 * Restrictions:
	 * - no access to entity manager or unit of work apis
	 * - no identifiers available if using an identity generator like sequences
	 * - Doctrine won't recognize changes on relations which are done here
	 * if this method is called by cascade persist
	 * - no creation of other entities allowed
	 *
	 * @see ShopProducts_Entity_Shop::prePersistCallback()
	 * @return boolean true if completed successfully else false.
	 */
	protected function performPrePersistCallback() {
		// echo 'inserting a record ...';
		// $this->validate();
		return true;
	}
	
	/**
	 * Post-Process the data after an insert operation.
	 * The event happens after the entity has been made persistant.
	 * Will be called after the database insert operations.
	 * The generated primary key values are available.
	 *
	 * Restrictions:
	 * - no access to entity manager or unit of work apis
	 *
	 * @see ShopProducts_Entity_Shop::postPersistCallback()
	 * @return boolean true if completed successfully else false.
	 */
	protected function performPostPersistCallback() {
		// echo 'inserted a record ...';
		return true;
	}
	
	/**
	 * Pre-Process the data prior a delete operation.
	 * The event happens before the entity managers remove operation is executed for this entity.
	 *
	 * Restrictions:
	 * - no access to entity manager or unit of work apis
	 * - will not be called for a DQL DELETE statement
	 *
	 * @see ShopProducts_Entity_Shop::preRemoveCallback()
	 * @return boolean true if completed successfully else false.
	 */
	protected function performPreRemoveCallback() {
		/*
		 * // delete workflow for this entity
		 * $result = Zikula_Workflow_Util::deleteWorkflow($this);
		 * if ($result === false) {
		 * $dom = ZLanguage::getModuleDomain('ShopProducts');
		 * return LogUtil::registerError(__('Error! Could not remove stored workflow.', $dom));
		 * }
		 */
		return true;
	}
	
	/**
	 * Post-Process the data after a delete.
	 * The event happens after the entity has been deleted.
	 * Will be called after the database delete operations.
	 *
	 * Restrictions:
	 * - no access to entity manager or unit of work apis
	 * - will not be called for a DQL DELETE statement
	 *
	 * @see ShopProducts_Entity_Shop::postRemoveCallback()
	 * @return boolean true if completed successfully else false.
	 */
	protected function performPostRemoveCallback() {
		// echo 'deleted a record ...';
		return true;
	}
	
	/**
	 * Pre-Process the data prior to an update operation.
	 * The event happens before the database update operations for the entity data.
	 *
	 * Restrictions:
	 * - no access to entity manager or unit of work apis
	 * - will not be called for a DQL UPDATE statement
	 * - changes on associations are not allowed and won't be recognized by flush
	 * - changes on properties won't be recognized by flush as well
	 * - no creation of other entities allowed
	 *
	 * @see ShopProducts_Entity_Shop::preUpdateCallback()
	 * @return boolean true if completed successfully else false.
	 */
	protected function performPreUpdateCallback() {
		// echo 'updating a record ...';
		// $this->validate();
		return true;
	}
	
	/**
	 * Post-Process the data after an update operation.
	 * The event happens after the database update operations for the entity data.
	 *
	 * Restrictions:
	 * - no access to entity manager or unit of work apis
	 * - will not be called for a DQL UPDATE statement
	 *
	 * @see ShopProducts_Entity_Shop::postUpdateCallback()
	 * @return boolean true if completed successfully else false.
	 */
	protected function performPostUpdateCallback() {
		// echo 'updated a record ...';
		return true;
	}
	
	/**
	 * Pre-Process the data prior to a save operation.
	 * This combines the PrePersist and PreUpdate events.
	 * For more information see corresponding callback handlers.
	 *
	 * @see ShopProducts_Entity_Shop::preSaveCallback()
	 * @return boolean true if completed successfully else false.
	 */
	protected function performPreSaveCallback() {
		// echo 'saving a record ...';
		// $this->validate();
		return true;
	}
	
	/**
	 * Post-Process the data after a save operation.
	 * This combines the PostPersist and PostUpdate events.
	 * For more information see corresponding callback handlers.
	 *
	 * @see ShopProducts_Entity_Shop::postSaveCallback()
	 * @return boolean true if completed successfully else false.
	 */
	protected function performPostSaveCallback() {
		// echo 'saved a record ...';
		return true;
	}
}
